# Generated by Django 2.0.1 on 2018-07-04 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.SlugField(max_length=100),
        ),
        migrations.AlterIndexTogether(
            name='order',
            index_together={('id', 'order_id')},
        ),
    ]
