# Generated by Django 2.0.1 on 2018-07-04 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20180705_0013'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='order',
            index_together=set(),
        ),
    ]
